=== robin-mijeanne/XML-M2/festival_cannes.dtd
<!-- DTD du TP autour du festival de Cannes  -->

<!-- - - - - -->
<!-- racine  -->
<!-- - - - - -->

<!ELEMENT festival_cannes (nationalites, artistes, films, jury, palmares)>
<!ATTLIST festival_cannes annee CDATA #REQUIRED>

<!-- - - - - - - - - - - - - - - - - - - - - -->
<!-- liste des nationalités et pays associés -->
<!-- - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT nationalites (pays+)>

<!ELEMENT pays (#PCDATA)>
<!ATTLIST pays code ID #REQUIRED>

<!-- - - - - - - - - - - - - - - - -->
<!-- description de chaque artiste -->
<!-- - - - - - - - - - - - - - - - -->

<!ELEMENT artistes (artiste+)>

<!ELEMENT artiste (prenom, nom, biographie?)>
<!ATTLIST artiste id   ID     #REQUIRED
                  sexe (M|F)  #REQUIRED
                  pays IDREFS #REQUIRED>

<!ELEMENT prenom     (#PCDATA)>
<!ELEMENT nom        (#PCDATA)>
<!ELEMENT biographie (#PCDATA)>

<!-- - - - - - - - - - - - - - - -->
<!-- description de chaque film  -->
<!-- - - - - - - - - - - - - - - -->

<!ELEMENT films (film+)>

<!ELEMENT film (titre, synopsis, casting, personnages)>
<!ATTLIST film id               ID     #REQUIRED
               pays             IDREFS #REQUIRED
               annee_production CDATA  #REQUIRED
               duree            CDATA  #REQUIRED
               date_sortie      CDATA  #REQUIRED>

<!ELEMENT titre    (#PCDATA)>

<!ELEMENT synopsis (#PCDATA)>

<!-- le casting référence les réalisateurs, scénaristes et -->
<!-- éventuellement chefs décorateurs du film              -->

<!ELEMENT casting EMPTY>
<!ATTLIST casting realisateurs     IDREFS #REQUIRED
                  scenaristes      IDREFS #REQUIRED
                  chef_decorateurs IDREFS #IMPLIED>

<!-- chaque personnage du film est incarné par un acteur (ou plusieurs, par ex. à des âges  -->
<!-- différents) et le contenu de la balise personnage est le nom du personnage en question -->

<!ELEMENT personnages (personnage+)>

<!ELEMENT personnage (#PCDATA)>
<!ATTLIST personnage incarne_par IDREFS #REQUIRED>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- description de chaque membre du jury et palmarès du festival  -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT jury (membre+)>

<!ELEMENT membre EMPTY>
<!ATTLIST membre artiste IDREF #REQUIRED
                 role    CDATA "membre">

<!ELEMENT palmares (prix+)>


<!-- il peut y avoir des films ou artistes ex aquo pour certains prix           -->


<!-- selon certaines règles comportant des exceptions et évoluant avec le temps -->

<!-- (cf. https://fr.wikipedia.org/wiki/Festival_de_Cannes)                     -->

<!ELEMENT prix (attribution+)>
<!ATTLIST prix nom    CDATA #REQUIRED

>

<!ELEMENT attribution EMPTY>
<!ATTLIST attribution film    IDREF #REQUIRED
                      artiste IDREF #IMPLIED
>

=== robin-mijeanne/XML-M2/festival_cannes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet href="main.xsl" type="text/xsl"?>

<!DOCTYPE festival_cannes SYSTEM "festival_cannes.dtd">

<festival_cannes annee="2016">

	<!-- nationalités des différents films, cf. https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3 -->
	<nationalites>
		<pays code="ZAF">Afrique du Sud</pays>
		<pays code="DEU">Allemagne</pays>
		<pays code="ARG">Argentine</pays>
		<pays code="AUS">Australie</pays>
		<pays code="AUT">Austriche</pays>
		<pays code="BEL">Belgique</pays>
		<pays code="BRA">Brésil</pays>
		<pays code="CAN">Canada</pays>
		<pays code="KOR">Corée du Sud</pays>
		<pays code="DNK">Danemark</pays>
		<pays code="ESP">Espagne</pays>
		<pays code="ETH">Éthiopie</pays>
		<pays code="USA">États-Unis</pays>
		<pays code="FRA">France</pays>
		<pays code="HUN">Hongrie</pays>
		<pays code="IRN">Iran</pays>
		<pays code="ITA">Italie</pays>
		<pays code="NZL">Nouvelle-Zélande</pays>
		<pays code="NLD">Pays-Bas</pays>
		<pays code="PHL">Philippines</pays>
		<pays code="ROU">Roumanie</pays>
		<pays code="GBR">Royaume-Uni</pays>
		<pays code="SWE">Suède</pays>
	</nationalites>

	<artistes>
		<artiste id="TeAb" sexe="F" pays="USA">
			<prenom>Terri</prenom>
			<nom>ABNEY</nom>
		</artiste>
		<artiste id="MaAd" sexe="F" pays="DEU">
			<prenom>Maren</prenom>
			<nom>ADE</nom>
		</artiste>
		<artiste id="ShAg" sexe="F" pays="IRN">
			<prenom>Shirin</prenom>
			<nom>AGHAKASHI</nom>
		</artiste>
		<artiste id="TaAl" sexe="F" pays="IRN">
			<prenom>Taraneh</prenom>
			<nom>ALIDOOSTI</nom>
		</artiste>
		<artiste id="PeAl" sexe="M" pays="ESP">
			<prenom>Pedro</prenom>
			<nom>ALMODÓVAR</nom>
			<biographie>
				De nationalité espagnole. Né en 1951 à Calzada de Calatrava (Espagne). 1980 : Pepi, Luci, Bom y otras chicas del Monton (Pepi, Luci, Bom et les autres) 1982 : Laberinto de pasiones (Le labyrinthe des passions) 1983 : Entre tinieblas (Dans les ténèbres) 1984/85 : Que he hecho yo para merecer esto?! (Qu'est-ce que j'ai fait pour mériter ça ?!) 1985/86 : Matador 1987 : Mujeres al borde de un ataque de nervios (Femmes au bord de la crise de nerfs) 1986 : La ley del deseo (La loi du désir) 1989 : Atame (Attache-moi) 1991 : Tacones lejanos (Talons aiguilles) 1993 : Kika 1995 : La flor de mi secreto (La fleur de mon secret) 1997 : Carne trémula (En chair et en os) 
			</biographie>
		</artiste>
		<artiste id="MEAn" sexe="F" pays="ROU">
			<prenom>Mara Elena</prenom>
			<nom>ANDREI</nom>
		</artiste>
		<artiste id="JoAn" sexe="M" pays="PHL">
			<prenom>Jomari</prenom>
			<nom>ANGELES</nom>
		</artiste>
		<artiste id="MiAp" sexe="F" pays="ROU">
			<prenom>Mirela</prenom>
			<nom>APOSTU</nom>
		</artiste>
		<artiste id="AnAr" sexe="F" pays="GBR">
			<prenom>Andrea</prenom>
			<nom>ARNOLD</nom>
		</artiste>
		<artiste id="SaAs" sexe="F" pays="IRN">
			<prenom>Sahra</prenom>
			<nom>ASADOLLAHE</nom>
		</artiste>
		<artiste id="OlAs" sexe="M" pays="FRA">
			<prenom>Olivier</prenom>
			<nom>ASSAYAS</nom>
			<biographie>
				Olivier Assayas est l’auteur d’une quinzaine de films. Après des études littéraires et artistiques, il réalise des court-métrages, collabore à des scénarios, notamment pour André Téchiné ("Rendez-Vous", "Le Lieu du crime") et écrit aux Cahiers du Cinéma (1980-85). Il est aussi l’auteur d’un livre d’entretiens avec Ingmar Bergman. Son premier film, "Désordre", primé à Venise (1986) l’impose comme l’un des cinéastes marquants de sa génération; "L’Eau froide" (1994) et "Irma Vep" (1996), présentés à Cannes, lui apportent une grande notoriété. Il est en Compétition au Festival de Cannes avec "Les Destinées sentimentales", "demonlover" et "Clean"qui vaudra à Maggie Cheung un Prix d’Interprétation Féminine. Le succès de ses deux derniers films, "L’Heure d’été" et "Carlos", récompensés par de nombreux prix internationaux, font de lui l’un des cinéastes français les plus reconnus. 
			</biographie>
		</artiste>
		<artiste id="StBa" sexe="M" pays="FRA">
			<prenom>Stéphane</prenom>
			<nom>BAK</nom>
		</artiste>
		<artiste id="MaBA" sexe="F" pays="IRN">
			<prenom>Maral</prenom>
			<nom>BANI ADAM</nom>
		</artiste>
		<artiste id="JaBa" sexe="M" pays="ESP">
			<prenom>Javier</prenom>
			<nom>BARDEM</nom>
		</artiste>
		<artiste id="JoBa" sexe="M" pays="USA">
			<prenom>Jon</prenom>
			<nom>BASS</nom>
		</artiste>
		<artiste id="NaBa" sexe="F" pays="FRA">
			<prenom>Nathalie</prenom>
			<nom>BAYE</nom>
		</artiste>
		<artiste id="ChrBe" sexe="M" pays="DEU">
			<prenom>Christian</prenom>
			<nom>BERKEL</nom>
		</artiste>
		<artiste id="ChaBe" sexe="M" pays="FRA">
			<prenom>Charles</prenom>
			<nom>BERLING</nom>
		</artiste>
		<artiste id="DaBi" sexe="M" pays="USA">
			<prenom>David</prenom>
			<nom>BIRKE</nom>
		</artiste>
		<artiste id="JoBl" sexe="M" pays="BEL">
			<prenom>Jonas</prenom>
			<nom>BLOQUET</nom>
		</artiste>
		<artiste id="SoBr" sexe="F" pays="BRA">
			<prenom>Sonia</prenom>
			<nom>BRAGA</nom>
		</artiste>
		<artiste id="JuBe" sexe="F" pays="BRA">
			<prenom>Julia</prenom>
			<nom>BERNAT</nom>
		</artiste>
		<artiste id="JuBi" sexe="F" pays="FRA">
			<prenom>Juliette</prenom>
			<nom>BINOCHE</nom>
		</artiste>
		<artiste id="DaBo" sexe="M" pays="FRA">
			<prenom>Damien</prenom>
			<nom>BONNARD</nom>
		</artiste>
		<artiste id="OlBo" sexe="M" pays="FRA">
			<prenom>Olivier</prenom>
			<nom>BONNAUD</nom>
		</artiste>
		<artiste id="AuBo" sexe="F" pays="FRA">
			<prenom>Audrey</prenom>
			<nom>BONNET</nom>
		</artiste>
		<artiste id="SiBo" sexe="F" pays="FRA">
			<prenom>Sigrid</prenom>
			<nom>BOUAZIZ</nom>
		</artiste>
		<artiste id="ChBo" sexe="M" pays="FRA">
			<prenom>Christian</prenom>
			<nom>BOUILLETTE</nom>
		</artiste>
		<artiste id="AnBr" sexe="F" pays="ROU">
			<prenom>Ana</prenom>
			<nom>BRĂNESCU</nom>
		</artiste>
		<artiste id="AlBr" sexe="M" pays="FRA">
			<prenom>Alex</prenom>
			<nom>BRENDEMÜHL</nom>
		</artiste>
		<artiste id="IlBr" sexe="F" pays="ROU">
			<prenom>Ilona</prenom>
			<nom>BREZOIANU</nom>
		</artiste>
		<artiste id="VaBT" sexe="F" pays="FRA">
			<prenom>Valeria</prenom>
			<nom>BRUNI TEDESCHI</nom>
			<biographie>
				Née à Turin , Valeria Bruni-Tedeschi a suivi des cours de théâtre à l'atelier Jean Darel, les cours de Blanche Salant au Centre Américain et a fréquenté l'Ecole des Amandiers de Patrice Chéreau à Nanterre. En 1983, elle débute en parallèle à la télévision dans Paolino, la Juste cause et la bonne raison de François Reichenbach, au théâtre dans Platonov de Tchekov mis en scène par Patrice Chéreau et au cinéma. Elle n'a cessé depuis lors, entre la France et l'Italie, de mener de front théâtre, cinéma et télévision. Pour la télévision, elle tourne dans L'Amoureuse de Jacques Doillon (1988), Petites de Noémie Lvovsky (1997), au théâtre on la voit dans des pièces de Kleist mises en scène par Pierre Romans (1983). Au cinéma elle joue dans Hôtel de France de Patrice Chéreau (1987), L'Homme qui a perdu son ombre d'Alain Tanner (1991), ou accompagnant les débuts de la réalisatrice Laurence Ferreira-Barbosa, dans Les Gens normaux n'ont rien d'exceptionnel (1993) pour lequel elle reçoit de nombreux prix. Fidèle à Patrice Chéreau, elle joue dans La Reine Margot (1993), Ceux qui m'aime prendront le train (1997), accompagne Noémie Lvovsky dans Oublie moi (1993) et La Vie ne me fait pas peur (1998). On la retrouve aussi dans La Seconda Volta de Mimmo Calopresti (1995), Mon homme de Bertrand Blier (1995), Encore de Pascal Bonitzer (1996), Nénette et Boni de Claire Denis (1996), La Couleur du mensonge de Claude Chabrol (1998), La Nourrice de Marco Bellochio (1998). Elle a récemment tourné dans Rien à faire (1999) de Marion Vernoux, Voci (2000) de Franco Giraldi et Inverno de Nina di Majo (2001).
			</biographie>
		</artiste>
		<artiste id="LiBu" sexe="F" pays="ROU">
			<prenom>Lia</prenom>
			<nom>BUGNAR</nom>
		</artiste>
		<artiste id="MeCa" sexe="F" pays="PHL">
			<prenom>Mercedes</prenom>
			<nom>CABRAL</nom>
		</artiste>
		<artiste id="LaCa" sexe="F" pays="FRA">
			<prenom>Laure</prenom>
			<nom>CALAMY</nom>
		</artiste>
		<artiste id="HuCa" sexe="M" pays="BRA">
			<prenom>Humberto</prenom>
			<nom>CARRÃO</nom>
		</artiste>
		<artiste id="NaCa" sexe="F" pays="FRA">
			<prenom>Natalie</prenom>
			<nom>CARTER</nom>
		</artiste>
		<artiste id="ViCa" sexe="M" pays="FRA">
			<prenom>Vincent</prenom>
			<nom>CASSEL</nom>
		</artiste>
		<artiste id="JWCh" sexe="M" pays="KOR">
			<prenom>Jin-Woong</prenom>
			<nom>CHO</nom>
		</artiste>
		<artiste id="AnCi" sexe="F" pays="ROU">
			<prenom>Ana</prenom>
			<nom>CIONTEA</nom>
		</artiste>
		<artiste id="BaCo" sexe="F" pays="BRA">
			<prenom>Barbara</prenom>
			<nom>COLEN</nom>
		</artiste>
		<artiste id="ZoCo" sexe="F" pays="BRA">
			<prenom>Zoraide</prenom>
			<nom>COLETO</nom>
		</artiste>
		<artiste id="MoCo" sexe="M" pays="PHL">
			<prenom>Mon</prenom>
			<nom>CONFIADO</nom>
		</artiste>
		<artiste id="AnCo" sexe="F" pays="FRA">
			<prenom>Anne</prenom>
			<nom>CONSIGNY</nom>
		</artiste>
		<artiste id="HuCo" sexe="M" pays="FRA">
			<prenom>Hugo</prenom>
			<nom>CONZELMANN</nom>
		</artiste>
		<artiste id="MaCo" sexe="F" pays="FRA">
			<prenom>Marion</prenom>
			<nom>COTILLARD</nom>
		</artiste>
		<artiste id="IoCr" sexe="F" pays="ROU">
			<prenom>Ioana</prenom>
			<nom>CRĂCIUNESCU</nom>
		</artiste>
		<artiste id="MaCs" sexe="M" pays="USA">
			<prenom>Marton</prenom>
			<nom>CSOKAS</nom>
		</artiste>
		<artiste id="InCu" sexe="F" pays="ESP">
			<prenom>Inma</prenom>
			<nom>CUESTA</nom>
		</artiste>
		<artiste id="AnDL" sexe="M" pays="SWE">
			<prenom>Anders</prenom>
			<nom>DANIELSEN LIE</nom>
		</artiste>
		<artiste id="JPDa" sexe="M" pays="BEL">
			<prenom>Jean-Pierre</prenom>
			<nom>DARDENNE</nom>
			<biographie>
